s =set()
n1 = input("Enter number")
s.add(int(n1))
n2 = input("Enter number")
s.add(int(n2))
n3 = input("Enter number")
s.add(int(n3))
n4 = input("Enter number")
s.add(int(n4))
n5 = input("Enter number")
s.add(int(n5))
n6 = input("Enter number")
s.add(int(n6))
print(s)