d = {}
name = input("Enter name of student: ")
lang = input("Enter language:")
d.update({name:lang})
name = input("Enter name of student: ")
lang = input("Enter language:")
d.update({name:lang})
name = input("Enter name of student: ")
lang = input("Enter language:")
d.update({name:lang})
name = input("Enter name of student: ")
lang = input("Enter language:")
d.update({name:lang})
print(d)